services:
  web:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    command: sh -c "python run.py"

  redis:
    container_name: pokarm_bot_redis
    image: redis:7.4.1-alpine3.20
    command: redis-server --appendonly no --maxmemory ${REDIS_MAXMEMORY:-1gb} --maxmemory-policy allkeys-lru
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  redis:

