"""Remove message_id

Revision ID: 99a1be22fa41
Revises: 2225a08e2b00
Create Date: 2024-11-10 20:01:09.064054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99a1be22fa41'
down_revision: Union[str, None] = '2225a08e2b00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('message_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
