"""Create recipe table

Revision ID: bf0c13567703
Revises: 
Create Date: 2024-11-09 16:44:14.436131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf0c13567703'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('message_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )    # ### end Alembic commands ###
    op.create_unique_constraint("uq_recipe_message_id", "recipes", ["message_id"])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
#    op.drop_constraint("uq_recipe_message_id", "recipes")
    op.drop_table("recipes")
    # ### end Alembic commands ###
